apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: ecommerce-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-api
        image: gateway-service:v1
        volumeMounts:
            - name: cert-volume
              mountPath: "/https"
              readOnly: true
            - name: config-volume
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
        imagePullPolicy: Never
        ports:
        - containerPort: 8080 # Phải đổi thành 8080 theo log bạn gửi
        - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Ép .NET lắng nghe trên cả 8080 và 443
        - name: ASPNETCORE_URLS
          value: "https://+:443;http://+:8080" 
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/tls.crt"
        - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
          value: "/https/tls.key"
        # --- GOOGLE WEB API SETTINGS ---
        - name: GoogleWebApiSettings__client_id
          value: "100244040042-7n5uq1tu0o3fb15gub1r190ijb7anl31.apps.googleusercontent.com"
        - name: GoogleWebApiSettings__project_id
          value: "projectcustomeridentityservice"
        - name: GoogleWebApiSettings__auth_uri
          value: "https://accounts.google.com/o/oauth2/auth"
        - name: GoogleWebApiSettings__token_uri
          value: "https://oauth2.googleapis.com/token"
        - name: GoogleWebApiSettings__auth_provider_x509_cert_url
          value: "https://www.googleapis.com/oauth2/v1/certs"
        - name: GoogleWebApiSettings__client_secret
          value: "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"

        # --- EXTERNAL PROVIDERS (Array mapping) ---
        - name: ExternalProviders__Schemes__0
          value: "Google"

        # --- INTERNAL AUTH ---
        # Chuyển localhost:7123 sang service name nội bộ
        - name: InternalAuth__TokenEndpoint
          value: "https://gateway-service:443/connect/token"
        - name: InternalAuth__ClientId
          value: "identityserver.internal"
        - name: InternalAuth__ClientSecret
          value: "secret"
        - name: InternalAuth__Scope
          value: "customer.internal"

        # --- CUSTOMER SERVICE ---
        - name: CustomerService__BaseUrl
          value: "http://customer-service:80"

        # --- JWT SETTINGS ---
        - name: JwtSettings__SecretKey
          value: "7244_Localhost_WebApi_JWT_SecretKey_2026_Secure_9fA3xP7QmL2Z"
        - name: JwtSettings__Issuer
          value: "https://gateway-service:443"
        - name: JwtSettings__Audience
          value: "https://gateway-service:443"
        - name: JwtSettings__ExpiryMinutes
          value: "60"       
      volumes:
      - name: config-volume
        configMap:
            name: yarp-config
      - name: cert-volume
        secret:
          secretName: gateway-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ecommerce-prod
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 # Map cổng 80 của Service vào 8080 của Container
      nodePort: 49730