apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service # Thống nhất tên service
  namespace: ecommerce-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-api
        image: customer-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080 # Cổng thực tế .NET đang lắng nghe
        volumeMounts:
         - name: dataprotection-storage
           mountPath: /home/app/.aspnet/DataProtection-Keys
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080" # Ép ứng dụng chạy trên 8080 để khớp với log
        - name: JwtSettings__Issuer
          value: "http://customer-service"
        - name: ConnectionStrings__CustomerAppLocal
          value: "User Id=CUSTOMER;Password=customer_pwd;Data Source=172.16.0.202:1521/FREEPDB1;Persist Security Info=True"
        - name: EcommerceApiGateWay__BaseUrl
          value: "https://gateway-service:443"
      volumes:
         - name: dataprotection-storage
           emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service # Gateway sẽ gọi tên này
  namespace: ecommerce-prod
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80         # Cổng giao tiếp nội bộ (Gateway gọi qua đây)
      targetPort: 8080 # Chuyển hướng vào cổng 8080 bên trong Pod