version: '3.8'

services:
  # --- API GATEWAY (Giữ HTTPS làm lớp bảo vệ bên ngoài) ---
  gateway-service:
    image: gateway-service:v1
    container_name: gateway_service
    ports:
      - "7123:443" # Máy ngoài gọi 7123 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.pem
      # GỌI SERVICE CON QUA HTTP (Nội bộ Docker)
      - InternalAuth__CustomerService__BaseUrl=http://customer-identity:80
      - InternalAuth__TokenEndpoint=http://customer-identity:80/connect/token
    volumes:
      # Cập nhật đường dẫn cert mới
      - D:\2026\Project\mini-project-ecommerce\certs:/https:ro
      # Cập nhật đường dẫn appsettings mới
      - D:\2026\Project\ecommerce-system\EcommerceApiGateway\EcommerceApiGateway\appsettings.json:/app/appsettings.json:ro
    networks:
      - ecommerce_net

  # --- CUSTOMER SERVICE (Chạy thuần HTTP bên trong) ---
  customer-identity:
    image: customeridentityserviceapi:latest
    container_name: customer_service
    ports:
      - "7244:80" # Mapping ra ngoài 7244 để bạn test trực tiếp nếu cần
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - JwtSettings__Issuer=http://customer-identity
      - ConnectionStrings__CustomerAppLocal=User Id=CUSTOMER;Password=customer_pwd;Data Source=host.docker.internal:1521/FREEPDB1;Persist Security Info=True
    volumes:
      # Cập nhật đường dẫn appsettings mới
      - D:\2026\Project\ecommerce-system\CustomerIdentityService\CustomerIdentityService.API\appsettings.json:/app/appsettings.json:ro
    networks:
      - ecommerce_net

networks:
  ecommerce_net:
    driver: bridge