apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-prod

# Danh sách các file riêng lẻ muốn gộp lại
resources:
  - proxy-config.yaml
  - deployment-gateway.yaml
  - deployment-customer.yaml