apiVersion: v1
kind: ConfigMap
metadata:
  name: yarp-config
  namespace: ecommerce-prod
data:
  appsettings.Production.json: |
    {
      "ReverseProxy": {
        "Routes": {
          "customer_route": {
            "ClusterId": "customer_cluster",
            "Match": {
              "Path": "/api/khach-hang/{**catch-all}"
            }
          }
        },
        "Clusters": {
          "customer_cluster": {
            "Destinations": {
              "customer_api": {
                "Address": "http://customer-service/"
              }
            }
          }
        }
      }
    }
