services:
  redis-cache:
    image: redis:alpine
    container_name: my-redis-lru-ttl
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy volatile-lru # cấu hình thuật toán lru và ttl
    ports:
      - "6380:6379" 
    restart: always
