ReverseProxy:
  Routes:
    product_service_api_route:
      ClusterId: "product_service_cluster"
      AuthorizationPolicy: "ProductPolicy"
      Match:
        Path: "/api/nganh-hang/quan-ly/{**catch-all}"
      Metadata:
        serviceName: "ProductCMSService"
  Clusters:
    product_service_cluster: # Phải khớp với ClusterId ở trên
      Destinations:
        product_service_node:
          Address: "https://ecom-product-service:443"