ReverseProxy:
  Routes:
    # Định nghĩa Route cho API Khách hàng
    customer-route:
      ClusterId: customer-cluster
      RateLimiterPolicy: "ratelimit-basic-policy"
      AuthorizationPolicy: CustomerService # Policy sẽ được định nghĩa trong code
      Match:
        Path: "/api/khach-hang/{**catch-all}"
  Clusters:
    # Định nghĩa Service Khách hàng bên dưới (Downstream)
    customer-cluster:
      Destinations:
        destination1:
          Address: "https://ecom-customer-identity:443" # Link service khách hàng của bạn