ReverseProxy:
  Routes:
    payment_service_api_route:
      ClusterId: "payment_service_cluster"
      RateLimiterPolicy: "ratelimit-order-policy"
      AuthorizationPolicy: PaymentService
      Match:
        Path: "/api/thanh-toan/{**catch-all}"
      Metadata:
        serviceName: "PaymentCMSService"
  Clusters:
    payment_service_cluster: # Phải khớp với ClusterId ở trên
      Destinations:
        payment_service_node:
          Address: "https://ecom-payment-service:443"